name: GvApp
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.0 # Mantén si usas ubicación
  url_launcher: ^6.0.20 # Mantén si usas abrir URLs
  permission_handler: ^10.2.0 # Mantén si usas permisos
  http: ^1.1.0 # Mantén si necesitas hacer solicitudes HTTP
  mobile_scanner: ^5.2.3 # Mantén si implementas escaneo de códigos QR
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  sensors_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/LOGO.jpg
    - assets/USER.jpg
    - assets/UP.jpg
